---
master:
  box: ubuntu/vivid64
  ram: 2048
  cpus: 4
  node:
  - name: clocker
    ip: 10.10.10.10
    forwarded_ports:
      - guest: 8080
        host: 8080
    shell:
    - touch ~/init.log
slave:
  box: ubuntu/vivid64
  count: 2
  prefix: byon-
  ram: 512
  cpus: 1
  shell:
  - touch ~/init.log
...