---
master:
  box: ubuntu/vivid64
  ram: 2048
  cpus: 4
  node:
  - name: clocker
    ip: 10.10.10.101
    forwarded_ports:
      - guest: 8081
        host: 8081
    shell:
    - export DEBIAN_FRONTEND=noninteractive; sudo apt-get install --yes openjdk-8-jre-headless
    - sudo ln -s /vagrant/files/.brooklyn /root/.brooklyn
    - sudo ln -s /vagrant/files/clocker-install.service /etc/systemd/system/clocker-install.service
    - sudo ln -s /vagrant/files/clocker.service /etc/systemd/system/clocker.service;
    - sudo systemctl start clocker-install clocker &
slave:
  box: ubuntu/vivid64
  count: 3
  hostname_template: byon%s
  ip_template: 10.10.100.%s
  ram: 512
  cpus: 1
  shell:
  - date > init.log
...